name: Helios Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: # manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Update Package Lists
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install valgrind g++ make --fix-missing
      - name: Build
        run: make -j
        working-directory: HeliosCLI
      - name: Set execute permissions for test script
        run: chmod +x ./runtests.sh
        working-directory: tests
      - name: Run general tests
        run: ./runtests.sh
        working-directory: tests

  embedded:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: make install
        working-directory: HeliosEmbedded
      - name: Build Binary
        run: make build
        working-directory: HeliosEmbedded
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: embedded firmware
          path: |
            HeliosEmbedded/helios.bin
            HeliosEmbedded/helios.elf
            HeliosEmbedded/helios.map
            HeliosEmbedded/helios.hex

  release:
    if: github.ref == 'refs/heads/master'
    needs: embedded
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for calculating version

      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "none")
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Check for existing tags
        id: check_tag
        run: |
          if [ "${{ env.tag }}" == "none" ]; then
            echo "No tags found. Skipping release."
            echo "skip_release=true" >> $GITHUB_ENV
          else
            echo "skip_release=false" >> $GITHUB_ENV
          fi

      - name: Calculate new version
        if: env.skip_release == 'false'
        id: calc_version
        run: |
          latest_tag=${{ env.tag }}
          commits_since_tag=$(git rev-list $latest_tag..HEAD --count)
          IFS='.' read -ra ADDR <<< "$latest_tag"
          new_version="${ADDR[0]}.${ADDR[1]}.$((commits_since_tag))"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: env.skip_release == 'false'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          body: |
            Release of version ${{ env.new_version }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (helios.bin)
        if: env.skip_release == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeliosEmbedded/helios.bin
          asset_name: helios.bin
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (helios.elf)
        if: env.skip_release == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeliosEmbedded/helios.elf
          asset_name: helios.elf
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (helios.map)
        if: env.skip_release == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeliosEmbedded/helios.map
          asset_name: helios.map
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (helios.hex)
        if: env.skip_release == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeliosEmbedded/helios.hex
          asset_name: helios.hex
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

