name: Helios Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Update Package Lists
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install valgrind g++ make --fix-missing
      - name: Build HeliosCLI
        run: make -j
        working-directory: HeliosCLI
      - name: Archive HeliosCLI artifacts
        run: |
          zip -r "helioscli.zip" .
        working-directory: HeliosCLI
      - name: Cache HeliosCLI Artifact
        uses: actions/cache@v4
        with:
          path: HeliosCLI/helioscli.zip
          key: ${{ runner.os }}-helioscli-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-helioscli-

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Restore HeliosCLI Artifact
        uses: actions/cache@v4
        with:
          path: HeliosCLI/helioscli.zip
          key: ${{ runner.os }}-helioscli-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-helioscli-
      - name: Set execute permissions for test script
        run: chmod +x ./runtests.sh
        working-directory: tests
      - name: Run general tests
        run: ./runtests.sh
        working-directory: tests

  embedded:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: make install
        working-directory: HeliosEmbedded
      - name: Build Binary
        run: make build
        working-directory: HeliosEmbedded
      - name: Archive HeliosEmbedded artifacts
        run: |
          zip -r "embedded-firmware.zip" .
        working-directory: HeliosEmbedded
      - name: Cache HeliosEmbedded Artifact
        uses: actions/cache@v4
        with:
          path: HeliosEmbedded/embedded-firmware.zip
          key: ${{ runner.os }}-embedded-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-embedded-

