name: Helios Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Update Package Lists
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install valgrind g++ make --fix-missing
      - name: Build HeliosCLI
        run: make -j
        working-directory: HeliosCLI
      - name: Archive HeliosCLI artifacts
        run: zip -r "helioscli.zip" .
        working-directory: HeliosCLI
      - name: Upload HeliosCLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helioscli-artifacts
          path: HeliosCLI/helioscli.zip

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Download HeliosCLI Artifact
        uses: actions/download-artifact@v4
        with:
          name: helioscli-artifacts
          path: ./HeliosCLI
      - name: Set execute permissions for test script
        run: chmod +x ./runtests.sh
        working-directory: tests
      - name: Run general tests
        run: ./runtests.sh
        working-directory: tests

  embedded:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: make install
        working-directory: HeliosEmbedded
      - name: Build Binary
        run: make build
        working-directory: HeliosEmbedded
      - name: Archive HeliosEmbedded artifacts
        run: zip -r "embedded-firmware.zip" .
        working-directory: HeliosEmbedded
      - name: Upload HeliosEmbedded Artifact
        uses: actions/upload-artifact@v4
        with:
          name: embedded-firmware
          path: HeliosEmbedded/embedded-firmware.zip

  wasm:
    needs: embedded
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Update Package Lists
        run: sudo apt-get update
      - name: Install Emscripten
        run: |
          sudo apt install -y cmake python3
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
        working-directory: HeliosEngine/HeliosLib
      - name: Build Webassembly
        run: |
          source ./emsdk/emsdk_env.sh
          make -j wasm
        working-directory: HeliosEngine/HeliosLib
